# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7d576b4b3b480358c7323f1beb1be86de38199708cdc4de5ae2783ec715b67dfb4fef36a5470e102528a148026fdf0b380f5c0e331f969502c0703185f91ca

test:
  secret_key_base: dff1cf44123fcf78b62c7864d33af5272ac4e59c14d5efc7ab31ff4f98daecece88d788d42798f5ba7b82301cd8ecca09c2555174c97efb1a81a029ce12b7d50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
